# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: '1.0'
# Stages can help you organize your steps in stages
stages:
  - clone
  - base

steps:
  clone:
    title: 'Cloning repository'
    type: 'git-clone'
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'
    git: 'github-motorefi'
    stage: 'clone'

  validate:
    title: Validating the Terraspace codebase
    type: freestyle
    stage: base
    working_directory: '${{clone}}/src'
    image: '${{MR_REGISTRY_PATH}}/iac-runner-base:latest'
    tag: '${{CF_REVISION}}'
    commands:
      - 'echo hello'
      - 'bundle update --bundler'
      - 'bundle install'
      - 'terraspace all validate'
